### ISSUE TITLE
Importing models / static objects / heightmap problem

### ISSUE THREAD

**Issue by vrpixel** [Ahrkylien/BF1942-Blender-add-on#2]
Hello, if I load models manually and load static objects, it works fine. When I batch import entire folder of all assets; it says that staticobject path does not exist. Is there a way to load only models that are needed for the level?
Also the scale of the terrain was wrong - models were floating in the air. Are there any certain settings I have to use?

**Comment by Ahrkylien** [comment]
Hi!
At the moment there is no way to auto-import the meshes that are used in a certain map.
This is on my to-do list.
As for your error: Can you please send the exact error message? And tell me what the exact steps were before you got it?
Before you import the terrain please fill in the yScale. You can find the value in init/terrain.con

**Comment by vrpixel** [comment]
sorry for late reply:

Read blend: D:\RIP\BF1942\bf1942_xmodels.blend
Python: Traceback (most recent call last):
  File "C:\Users\GTX1060\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BF1942-Blender-add-on-main\src\utils.py", line 222, in execute
    static_objects = bf42_ParseCon(path)
  File "C:\Users\GTX1060\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BF1942-Blender-add-on-main\src\staticObjects.py", line 33, in bf42_ParseCon
    with open(filename, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '//..\\..\\@BF1942\\xmaps\\Stalingrad\\StaticObjects.con'

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\GTX1060\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BF1942-Blender-add-on-main\src\utils.py", line 222, in execute
    static_objects = bf42_ParseCon(path)
  File "C:\Users\GTX1060\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BF1942-Blender-add-on-main\src\staticObjects.py", line 33, in bf42_ParseCon
    with open(filename, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '//..\\..\\@BF1942\\xmaps\\Stalingrad\\StaticObjects.con'

location: <unknown location>:-1


This is in a project that loaded entire standardmesh folder, 1445 objects?

**Comment by vrpixel** [comment]
still getting an error

Read blend: D:\RIP\BF1942\bf1942_xmodels.blend
Python: Traceback (most recent call last):
  File "C:\Users\GTX1060\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BF1942-Blender-add-on-main\src\utils.py", line 222, in execute
    static_objects = bf42_ParseCon(path)
  File "C:\Users\GTX1060\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BF1942-Blender-add-on-main\src\staticObjects.py", line 33, in bf42_ParseCon
    with open(bpy.path.abspath(path), 'r') as fp:
NameError: name 'bpy' is not defined

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\GTX1060\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BF1942-Blender-add-on-main\src\utils.py", line 222, in execute
    static_objects = bf42_ParseCon(path)
  File "C:\Users\GTX1060\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BF1942-Blender-add-on-main\src\staticObjects.py", line 33, in bf42_ParseCon
    with open(bpy.path.abspath(path), 'r') as fp:
NameError: name 'bpy' is not defined

location: <unknown location>:-1

**Comment by Ahrkylien** [comment]
that should be fixed now

**Comment by vrpixel** [comment]
No error now, but it all looks glitched. Maybe because i imported all meshes with standard 0.01 scale, and then scaled it to 1.0.
Will try to reimport all models, and then try staticobjects.

**Comment by Ahrkylien** [comment]
Great,
Yes, you should not scale the objects after importing.
The setting called 'scene scale' should only be changed at the beginning. I
recommend to set it to 0.1

You CAN scale it up after importing, but then you really need to know what
you are doing. I.e. change 'scene scale' accordingly.

**Comment by vrpixel** [comment]
I think you missed my edit, yes, I got it working now.
Which file is responsible for foliage?

**Comment by vrpixel** [comment]
I misclicked

**Comment by vrpixel** [comment]
Sorry I misclicked. Yes, I got it working, and will try now with expansion packs.
Is there any way to add terrain textures, or at least vertex blending?
I'm not sure how it was done in original game.

**Comment by Ahrkylien** [comment]
I assume you already imported the hightmap of the terrain. Now you will
have to manually create a single image out of all terrain tiles. In blender
you add this image to the material, the uv is already generated.
Furthermore there is a detail texture. This texture should be added to the
material via a new uv map.
The detail texture should be repeated over every square face on the terrain
mesh.
At the end you will have to multiply both colors in the material.

This all requires quite some blender knowledge though..

**Comment by vrpixel** [comment]
Awesome. I've been merging tiles of terrain textures for BF2 before.
Great job so far.

Perhaps a suggestion, until fix is in place - create placeholder collection for missing objects?
This way maybe I can import back missing models via other means.

Really nice to see work done for such a classic. Thumbs up!

**Comment by Ahrkylien** [comment]
Thanks!!
Also thanks for the feedback. That's always welcome.
Adding a list for the placement of objects and improving the import of the
staticObjects.con is on the top of my ToDo list. If object meshes cant be
found then there will be a list of missing meshes like in BC.
But for now im distracted with adding a lightmap export function ;)

Have fun with whatever project you are busy with!!
